export { createClient, Client, ClientOptions } from './client/createClient'
export { linkTypeMap } from './client/linkTypeMap'
export { Observable } from 'rxjs'
export { MapType } from './client/typeSelection'
export { createDefaultFetcher, ClientError } from './fetcher'
