import Prism from 'prismjs'
import 'prismjs/components/prism-jsx'
import 'prismjs/components/prism-go'
import 'prismjs/components/prism-python'
import 'prismjs/components/prism-markdown'
import 'prismjs/themes/prism-tomorrow.css'

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0fsbApDRXfd
 */
import {
    TabsTrigger,
    TabsList,
    TabsContent,
    Tabs,
} from '@app/components/ui/tabs'
import { useEffect, useState } from 'react'

const jsCode = `
import { createClient, everything } from '@genql/my-lib'

await createClient().query({
    User: {
        name: true,
        surname: true,
        address: {
            ...everything,
        }
    }
})`
const goCode = `
// coming soon
import (
    "github.com/genql/genql/runtime/golang"
)

client := genql.NewClient()
user := client.User(&genql.UserArgs{
    ID: "1",
})

`
const pythonCode = `
# coming soon
from genql import Client

client = Client()

user = await client.user(args={'id'="1"}, select={'name': True, 'surname': True, 'address': True})


`

export function CodeTabs() {
    const [value, setValue] = useState('node')
    useEffect(() => {
        Prism.highlightAll()
    }, [value])
    return (
        <Tabs
            className='min-h-[400px]'
            value={value}
            key={value}
            onValueChange={setValue}
            defaultValue='node'
        >
            <TabsList>
                <TabsTrigger defaultChecked value='node'>
                    JavaScript
                </TabsTrigger>
                <TabsTrigger value='python'>Python</TabsTrigger>
                <TabsTrigger value='go'>Go</TabsTrigger>
                <TabsTrigger disabled value='more'>
                    and more...
                </TabsTrigger>
            </TabsList>
            <TabsContent value='node'>
                <pre className='language-javascript overflow-hidden bg-[#011627] text-white rounded-lg'>
                    <code className=''>{jsCode}</code>
                </pre>
            </TabsContent>
            <TabsContent value='python'>
                <pre className='language-python overflow-hidden bg-[#011627] text-white rounded-lg'>
                    <code className=''>{pythonCode}</code>
                </pre>
            </TabsContent>
            <TabsContent value='go'>
                <pre className='language-go overflow-hidden bg-[#011627] text-white rounded-lg'>
                    <code className=''>{goCode}</code>
                </pre>
            </TabsContent>
        </Tabs>
    )
}
