/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0fsbApDRXfd
 */
import { TabsTrigger, TabsList, TabsContent, Tabs } from "@app/components/ui/tabs"

export function CodeTabs() {
  return (
    <Tabs>
      <TabsList>
        <TabsTrigger value="node">Node</TabsTrigger>
        <TabsTrigger value="python">Python</TabsTrigger>
        <TabsTrigger value="go">Go</TabsTrigger>
        <TabsTrigger value="java">Java</TabsTrigger>
        <TabsTrigger value="kotlin">Kotlin</TabsTrigger>
      </TabsList>
      <TabsContent className="p-4 bg-[#011627] text-white rounded-lg" value="node">
        <pre>
          <code>
            {`import OpenAI from 'openai';
        
        async function main() {
          const openai = new OpenAI();
        
          const completion = await openai.chat.completions.create({
            model: 'gpt-3.5-turbo',
            messages: [{
              role: 'user',
              content: 'Say this is a test',
            }],
          });
        
          console.log(completion.choices[0]?.message?.content);
        }
        
        main();`}
          </code>
        </pre>
      </TabsContent>
      <TabsContent className="p-4 bg-[#011627] text-white rounded-lg" value="python">
        <pre>
          <code>
            {`import openai
        
        def main():
            openai.api_key = 'your-api-key'
            response = openai.Completion.create(
              model="text-davinci-003",
              prompt="Translate the following English text to French: '{}'",
              max_tokens=60
            )
        
            print(response.choices[0].text.strip())
        
        main()`}
          </code>
        </pre>
      </TabsContent>
      <TabsContent className="p-4 bg-[#011627] text-white rounded-lg" value="go">
        <pre>
          <code>
            {`package main
        
            "fmt"
            "github.com/OpenAI/golang-sdk/openai"
        
        func main() {
            client := openai.Client{ApiKey: "your-api-key"}
            resp, err := client.Completions.Create(openai.CompletionRequest{
                Model: "text-davinci-003",
                Prompt: "What is the capital of France?",
                MaxTokens: 5,
            })
            if err != nil {
                panic(err)
            }
            fmt.Println(resp.Choices[0].Text)
        }`}
          </code>
        </pre>
      </TabsContent>
      <TabsContent className="p-4 bg-[#011627] text-white rounded-lg" value="java">
        <pre>
          <code>
            {`import com.theopenai.api.OpenAIClient;
        
        public class OpenAIExample {
            public static void main(String[] args) {
                OpenAIClient client = new OpenAIClient("your-api-key");
                CompletionRequest request = new CompletionRequest();
                request.setModel("text-davinci-003");
                request.setPrompt("What is the capital of France?");
                request.setMaxTokens(5);
                String response = client.createCompletion(request).getChoices().get(0).getText();
                System.out.println(response);
            }
        }`}
          </code>
        </pre>
      </TabsContent>
      <TabsContent className="p-4 bg-[#011627] text-white rounded-lg" value="kotlin">
        <pre>
          <code>
            {`import ai.openai.kotlin.*
        
        fun main() {
            val client = OpenAIClient("your-api-key")
            val response = client.completions.create(CompletionRequest(
                model = "text-davinci-003",
                prompt = "What is the capital of France?",
                maxTokens = 5
            ))
            println(response.choices.first().text)
        }`}
          </code>
        </pre>
      </TabsContent>
    </Tabs>
  )
}
