name: Release

on:
    push:
        branches:
            - master
    workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
            contents: write
            pull-requests: write
            actions: write
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                  submodules: true

            - name: Setup Node.js 20.x
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: false
            - name: Install pnpm dependencies (with cache)
              uses: covbot/pnpm-install-with-cache@v1
            - run: pnpm buildall
            - run: pnpm genall
            - run: pnpm test
            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm changeset publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
